name: Build Windows Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log xl_pdf to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: docker build -t starfall07g/window:latest .

      - name: List files xl_pdf data/out
        run: docker run --rm starfall07g/window:latest powershell -Command "Get-ChildItem -Path C:\app\data\in\p1\xl_pdf -Recurse"

      - name: Push Docker Image
        run: docker push starfall07g/window:latest