name: Manual Deploy With Git Tag

on:
  workflow_dispatch: # Must be indented 2 spaces
    inputs:          # Must be indented 4 spaces
      tag:           # Must be indented 6 spaces
        description: "Git tag to deploy..."
        required: true
        type: string
      environment:
        description: "staging (default), prod"
        required: true
        type: choice
        options:
          - staging
          - prod
        default: staging
      reason:
        description: "Reason for deploying the tag"
        required: true
        type: string

jobs:
  detect-environment:
    name: Detect Environment
    runs-on: ubuntu-latest
    steps:
      - id: set-env
        run: |
          echo "Hi"